[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["Ryan O'Beirne <ryanobeirne@ryanobeirne.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"

